description of commands

diff --git a/scripts/slack b/scripts/slack
--- a/scripts/slack
+++ b/scripts/slack
@@ -1,5 +1,6 @@
 #!/usr/bin/env bash
-# shellcheck shell=sh
+
+# Description: Sends message to slack channel.
 
 MESSAGE="$1"
 CHANNEL="#general"
@@ -16,46 +17,45 @@ eval set -- "$options"
 
 while true; do
     case $1 in
-        --icon)
-            ICON="$2"
-            shift 2
-            ;;
-        --username)
-            USERNAME="$2"
-            shift 2
-            ;;
-        --channel)
-            CHANNEL="$2"
-            shift 2
-            ;;
-        --)
-            MESSAGE="${*:2}"
-            shift
-            break
-            ;;
-        *)
-            echo "Internal error!"
-            exit 1
-            ;;
+    --icon)
+        ICON="$2"
+        shift 2
+        ;;
+    --username)
+        USERNAME="$2"
+        shift 2
+        ;;
+    --channel)
+        CHANNEL="$2"
+        shift 2
+        ;;
+    --)
+        MESSAGE="${*:2}"
+        shift
+        break
+        ;;
+    *)
+        echo "Internal error!"
+        exit 1
+        ;;
     esac
 done
 
 json_init() {
     TMP_FILE=$(mktemp)
-    echo "{}">"$TMP_FILE"
+    echo "{}" >"$TMP_FILE"
 }
 
 json_set() {
     key="$1"
     value=${*:2}
 
-    content=$(jq ".$key = \"$value\"" "$TMP_FILE") && echo "$content">"$TMP_FILE"
+    content=$(jq ".$key = \"$value\"" "$TMP_FILE") && echo "$content" >"$TMP_FILE"
 }
 
 json_destroy() {
     rm "$TMP_FILE"
 }
-
 
 INVOKER=$(ps -ocmd= -p $PPID)
 FROM="$(whoami)@$(hostname)"
